name: 🐛 Bug Report
description: Report a bug or unexpected behavior in ServalSheets
labels: ['bug', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug!

        Please fill out the sections below to help us investigate the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I've searched existing issues and this is not a duplicate
          required: true
        - label: I'm using the latest version of ServalSheets
          required: true
        - label: I've checked the [troubleshooting guide](https://github.com/khill1269/servalsheets/blob/main/docs/guides/TROUBLESHOOTING.md)
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: "When I call sheets_data with action='read', I get an AUTH_REQUIRED error even though I'm authenticated..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior
      placeholder: |
        1. Start server with STDIO transport
        2. Authenticate with sheets_auth action="login"
        3. Call sheets_data with spreadsheetId="..." and action="read"
        4. Observe error message
      value: |
        1.
        2.
        3.
        4.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: 'Data should be returned from the spreadsheet...'
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: 'Error: AUTH_REQUIRED is thrown...'
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Include error messages, stack traces, or relevant log output
      render: shell
      placeholder: |
        {"level":"error","message":"Authentication required",...}
    validations:
      required: false

  - type: dropdown
    id: transport
    attributes:
      label: Transport
      description: Which MCP transport are you using?
      options:
        - STDIO (Claude Desktop)
        - HTTP/SSE
        - Streamable HTTP
        - Other (specify in additional context)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: ServalSheets Version
      description: Output of `npm list servalsheets` or Docker image tag
      placeholder: '1.6.0'
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: Output of `node --version`
      placeholder: 'v20.10.0'
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux (Ubuntu/Debian)
        - Linux (RHEL/Fedora)
        - Linux (Other)
        - Windows
        - Docker
        - Other (specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: tool
    attributes:
      label: Tool(s) Affected
      description: Which ServalSheets tool(s) are affected?
      multiple: true
      options:
        - sheets_auth
        - sheets_core
        - sheets_data
        - sheets_format
        - sheets_dimensions
        - sheets_visualize
        - sheets_collaborate
        - sheets_advanced
        - sheets_transaction
        - sheets_quality
        - sheets_history
        - sheets_confirm
        - sheets_analyze
        - sheets_fix
        - sheets_composite
        - sheets_session
        - sheets_templates
        - sheets_bigquery
        - sheets_appsscript
        - sheets_webhook
        - sheets_dependencies
        - Unknown/Not sure

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, related issues, etc.)
    validations:
      required: false
