name: ✨ Feature Request
description: Suggest a new feature or enhancement for ServalSheets
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

        Before submitting, please check if a similar feature has already been requested.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I've searched existing issues and this feature hasn't been requested
          required: true
        - label: I've checked the [roadmap](https://github.com/khill1269/servalsheets/blob/main/docs/planning/TODO.md) to see if this is already planned
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? (Optional but helpful)
      placeholder: "I'm always frustrated when I need to manually format cells after reading data..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see
      placeholder: "Add a new action to sheets_format that automatically applies formatting based on data types..."
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which category does this feature fall under?
      options:
        - New Tool (entirely new sheets_* tool)
        - New Action (new action in existing tool)
        - Enhancement (improve existing action)
        - Performance (speed/efficiency improvement)
        - Developer Experience (easier to use/configure)
        - Documentation (guides, examples)
        - Infrastructure (deployment, monitoring)
        - Other (specify in description)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (your perspective)
      description: How important is this feature to you?
      options:
        - Critical (blocking my use case)
        - High (would significantly improve my workflow)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "I could use sheets_format multiple times, but that's inefficient..."
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Show how you'd use this feature (pseudo-code is fine)
      render: typescript
      placeholder: |
        // Example: Auto-format based on data type
        await sheets_format({
          action: "auto_format",
          spreadsheetId: "abc123",
          range: "A1:D100",
          detectTypes: true  // Automatically detect numbers, dates, currency
        });
    validations:
      required: false

  - type: dropdown
    id: willingness
    attributes:
      label: Willingness to Contribute
      description: Would you be willing to help implement this feature?
      options:
        - Yes, I can submit a PR
        - Yes, I can help test
        - Maybe, with guidance
        - No, just suggesting
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups here
    validations:
      required: false
