/**
 * ServalSheets - Action Counts
 *
 * Source of truth for the number of actions per tool.
 * This file has NO dependencies to avoid circular imports.
 *
 * Auto-generated by scripts/generate-metadata.ts
 */

export const ACTION_COUNTS: Record<string, number> = {
  sheets_advanced: 31,
  sheets_analyze: 18,
  sheets_appsscript: 18,
  sheets_auth: 4,
  sheets_bigquery: 17,
  sheets_collaborate: 35,
  sheets_composite: 11,
  sheets_confirm: 5,
  sheets_core: 19,
  sheets_data: 19,
  sheets_dependencies: 7,
  sheets_dimensions: 28,
  sheets_federation: 4,
  sheets_fix: 6,
  sheets_format: 24,
  sheets_history: 7,
  sheets_quality: 4,
  sheets_session: 26,
  sheets_templates: 8,
  sheets_transaction: 6,
  sheets_visualize: 18,
  sheets_webhook: 7,
};

/**
 * Total number of tools (calculated)
 */
export const TOOL_COUNT = Object.keys(ACTION_COUNTS).length;

/**
 * Total number of actions across all tools (calculated)
 */
export const ACTION_COUNT = Object.values(ACTION_COUNTS).reduce((sum, count) => sum + count, 0);
