/**
 * Full Tool and Action Descriptions for ServalSheets (25 tools, 407 actions)
 *
 * These descriptions are auto-generated from handler docstrings and schema definitions.
 * DO NOT EDIT MANUALLY — update the corresponding handler or schema file instead.
 *
 * Use cases:
 * - MCP Tool Descriptions (sent during discovery if DEFERRED_DESCRIPTIONS=false)
 * - LLM prompting (context for decision-making)
 * - Documentation generation
 */

import { z } from 'zod';
import { ErrorDetailSchema, ResponseMetaSchema, type ToolAnnotations } from './shared.js';

// Full descriptions for each tool
// Format: { toolName: { actionName: 'description', ... }, ... }

const TOOL_DESCRIPTIONS = {
  sheets_core: {
    create: 'Create a new Google Spreadsheet',
    get: 'Get spreadsheet metadata (title, locale, timezone, properties)',
    list: 'List all spreadsheets in My Drive (paginated)',
    list_sheets: 'List all sheets/tabs in a spreadsheet',
    add_sheet: 'Add a new sheet/tab to a spreadsheet',
    update_sheet: 'Update sheet properties (title, hidden, frozen rows/columns)',
    delete_sheet: 'Delete a sheet/tab (destructive, requires confirmation)',
    batch_get: 'Fetch metadata for multiple spreadsheets in parallel',
    copy: 'Copy entire spreadsheet (creates new spreadsheet)',
    copy_sheet_to: 'Copy a sheet from one spreadsheet to another',
    duplicate_sheet: 'Duplicate a sheet within the same spreadsheet',
    move_sheet: 'Move a sheet to a different position within the spreadsheet',
    clear_sheet: 'Clear all cell values from a sheet (destructive)',
    batch_delete_sheets: 'Delete multiple sheets at once (destructive)',
    batch_update_sheets: 'Update multiple sheets in a single batch operation',
    get_sheet: 'Get full metadata for a specific sheet (including grid data)',
    get_comprehensive: 'Get complete spreadsheet structure (all sheets, metadata, grid data)',
    get_url: 'Get the web URL for a spreadsheet',
    update_properties: 'Update spreadsheet properties (title, locale, timezone, theme, auto-recalc)',
    describe_workbook: 'Get a human-readable description of spreadsheet structure',
    workbook_fingerprint: 'Generate a fingerprint of spreadsheet structure (for caching/dedup)',
  },
  sheets_data: {
    read: 'Read cell values from a range',
    write: 'Write cell values to a range',
    append: 'Append rows to a sheet (finds first empty row)',
    batch_read: 'Read multiple ranges in parallel (40% faster than sequential)',
    batch_write: 'Write to multiple ranges in a single batch update',
    find_replace: 'Find and replace text/values in a range (with regex support)',
    clear: 'Clear cell values from a range (destructive)',
    batch_clear: 'Clear multiple ranges at once (destructive)',
    copy_paste: 'Copy from one range and paste to another (supports special paste modes)',
    cut_paste: 'Cut from one range and paste to another (moving cells)',
    auto_fill: 'Auto-fill a range based on pattern (drag-down behavior)',
    set_hyperlink: 'Add hyperlink to a cell',
    clear_hyperlink: 'Remove hyperlink from a cell',
    add_note: 'Add a comment/note to a cell',
    get_note: 'Read the note/comment from a cell',
    clear_note: 'Delete a note/comment from a cell',
    merge_cells: 'Merge cells in a range (combine multiple cells into one)',
    unmerge_cells: 'Split merged cells back into individual cells',
    get_merges: 'Get all merged cell ranges in a sheet',
    detect_spill_ranges: 'Detect array formulas and their spill ranges',
    cross_read: 'Read and merge data from multiple spreadsheets',
    cross_write: 'Write data to a different spreadsheet',
    smart_fill: 'Intelligently fill a range based on context (AI-assisted)',
  },
  sheets_format: {
    set_format: 'Apply number format to cells (currency, percentage, date, etc.)',
    set_background: 'Set cell background color',
    set_text_format: 'Set text formatting (bold, italic, font, size, color)',
    batch_format: 'Apply multiple formatting changes in a single operation',
    set_borders: 'Set cell borders (top, bottom, left, right, inner, outer)',
    set_alignment: 'Set text alignment (horizontal, vertical, wrap)',
    set_number_format: 'Apply number format pattern',
    clear_format: 'Remove all formatting from a range',
    suggest_format: 'AI-powered formatting suggestions based on cell values',
    auto_fit: 'Auto-resize rows/columns to fit content',
    apply_preset: 'Apply preset styles (header, alternating rows, total row, etc.)',
    add_conditional_format_rule: 'Add conditional formatting rule (color scale, data bar, icon set, etc.)',
    update_conditional_format: 'Update existing conditional format rule',
    delete_conditional_format: 'Remove conditional format rule',
    list_conditional_formats: 'Get all conditional formatting rules in a sheet',
    set_data_validation: 'Add data validation (dropdown, number range, text pattern, etc.)',
    clear_data_validation: 'Remove data validation',
    list_data_validations: 'Get all data validation rules (paginated)',
    sparkline_add: 'Add sparkline (mini chart in a cell)',
    sparkline_clear: 'Remove sparkline',
    sparkline_get: 'Read sparkline configuration',
    set_rich_text: 'Set rich text formatting (different formats in same cell)',
    build_dependent_dropdown: 'Create cascading dropdown (second dropdown depends on first)',
  },
  sheets_dimensions: {
    insert: 'Insert rows or columns at a position',
    delete: 'Delete rows or columns (destructive)',
    resize: 'Set exact height (rows) or width (columns) in pixels',
    auto_resize: 'Auto-fit rows/columns to content',
    hide: 'Hide rows or columns (not deleted, just hidden)',
    show: 'Show hidden rows or columns',
    freeze: 'Freeze rows/columns so they stay visible when scrolling',
    sort_range: 'Sort a range by one or more columns',
    set_basic_filter: 'Apply filter to a range (hide rows by criteria)',
    clear_basic_filter: 'Remove basic filter',
    get_basic_filter: 'Get current filter criteria',
    create_filter_view: 'Create a filter view (non-destructive filtered view)',
    update_filter_view: 'Update filter view criteria',
    delete_filter_view: 'Delete filter view',
    get_filter_view: 'Get filter view configuration',
    list_filter_views: 'List all filter views in a sheet',
    create_slicer: 'Create slicer (interactive filter widget)',
    update_slicer: 'Update slicer configuration',
    delete_slicer: 'Delete slicer',
    list_slicers: 'List all slicers in a sheet',
    group: 'Group rows or columns (for collapsible outline)',
    ungroup: 'Ungroup rows or columns',
    move: 'Move rows or columns to new position',
    delete_duplicates: 'Remove duplicate rows (destructive)',
    randomize_range: 'Randomly shuffle rows or values',
    text_to_columns: 'Split text into columns (delimiter-based)',
    trim_whitespace: 'Remove leading/trailing whitespace from all cells',
    append: 'Append rows to a sheet',
  },
  sheets_advanced: {
    add_named_range: 'Create a named range (reusable alias for a range)',
    update_named_range: 'Update named range definition',
    delete_named_range: 'Delete named range',
    get_named_range: 'Get named range details (name, range, scope)',
    list_named_ranges: 'List all named ranges in spreadsheet',
    create_named_function: 'Create a named function (custom formula function)',
    update_named_function: 'Update named function definition',
    delete_named_function: 'Delete named function',
    get_named_function: 'Get named function details',
    list_named_functions: 'List all named functions',
    add_protected_range: 'Create protected range (restrict editing)',
    update_protected_range: 'Update protection rules for a range',
    delete_protected_range: 'Remove protection from a range',
    list_protected_ranges: 'List all protected ranges',
    add_banding: 'Add alternating color banding to rows/columns',
    update_banding: 'Update banding configuration',
    delete_banding: 'Remove banding',
    list_banding: 'List all banding rules',
    create_table: 'Create a table (structured data range)',
    update_table: 'Update table configuration',
    delete_table: 'Delete table',
    list_tables: 'List all tables in sheet',
    set_table_column_properties: 'Set column properties in table (data validation, formula)',
    rename_table_column: 'Rename table column',
    add_person_chip: 'Add person chip (mention/reference) to cell',
    add_drive_chip: 'Add Drive file chip to cell',
    add_rich_link_chip: 'Add rich link chip to cell',
    list_chips: 'List all chips in sheet',
    set_metadata: 'Set custom metadata on spreadsheet or range',
    get_metadata: 'Get custom metadata',
    delete_metadata: 'Delete custom metadata',
  },
  sheets_visualize: {
    chart_create: 'Create a chart (pie, bar, line, scatter, combo, etc.)',
    chart_update: 'Update chart configuration (title, data range, type, etc.)',
    chart_delete: 'Delete chart',
    chart_list: 'List all charts in spreadsheet',
    chart_get: 'Get chart configuration and metadata',
    chart_move: 'Move chart to new position',
    chart_resize: 'Resize chart',
    chart_update_data_range: 'Update data source for chart',
    chart_add_trendline: 'Add trendline to chart',
    chart_remove_trendline: 'Remove trendline',
    pivot_create: 'Create pivot table',
    pivot_update: 'Update pivot table configuration',
    pivot_delete: 'Delete pivot table',
    pivot_list: 'List all pivot tables',
    pivot_get: 'Get pivot table configuration',
    pivot_refresh: 'Refresh pivot table data',
    suggest_chart: 'AI-powered chart suggestions based on data',
    suggest_pivot: 'AI-powered pivot table suggestions',
  },
  sheets_collaborate: {
    share_add: 'Grant permission to user/group/domain/public',
    share_update: 'Update permission level for a user/group',
    share_remove: 'Revoke permission',
    share_list: 'List all users with permission',
    share_get: 'Get permission details for a user',
    share_transfer_ownership: 'Transfer spreadsheet ownership',
    share_set_link: 'Enable/disable sharing link access',
    share_get_link: 'Get current sharing link settings',
    comment_add: 'Add comment to a cell',
    comment_update: 'Update comment text',
    comment_delete: 'Delete comment',
    comment_resolve: 'Mark comment as resolved',
    comment_reopen: 'Reopen resolved comment',
    comment_get: 'Get comment details',
    comment_list: 'List comments in sheet (paginated)',
    comment_add_reply: 'Reply to a comment',
    comment_update_reply: 'Update comment reply',
    comment_delete_reply: 'Delete comment reply',
    version_create_snapshot: 'Create a named checkpoint of current state',
    version_delete_snapshot: 'Delete snapshot',
    version_list_snapshots: 'List all snapshots',
    version_restore_snapshot: 'Restore spreadsheet to a snapshot',
    version_snapshot_status: 'Get snapshot creation status',
    version_list_revisions: 'List all revisions (version history)',
    version_get_revision: 'Get revision details',
    version_compare: 'Compare two revisions',
    version_restore_revision: 'Restore spreadsheet to a revision',
    version_keep_revision: 'Mark revision as keep-forever',
    version_export: 'Export revision as XLSX/CSV/PDF',
    approval_create: 'Create approval workflow',
    approval_get_status: 'Get approval status',
    approval_approve: 'Approve a pending action',
    approval_reject: 'Reject a pending action',
    approval_delegate: 'Delegate approval to another user',
    approval_list_pending: 'List pending approvals',
    approval_cancel: 'Cancel approval workflow',
    label_apply: 'Apply label to spreadsheet',
    label_list: 'List available labels',
    label_remove: 'Remove label',
    list_access_proposals: 'List pending access requests',
    resolve_access_proposal: 'Approve or deny access request',
  },
  sheets_composite: {
    import_csv: 'Import CSV data into spreadsheet',
    import_xlsx: 'Import Excel workbook',
    export_xlsx: 'Export spreadsheet as Excel file',
    export_large_dataset: 'Stream export large dataset',
    get_form_responses: 'Get responses from Google Form connected to spreadsheet',
    smart_append: 'Intelligently append data (detects headers, handles duplicates)',
    deduplicate: 'Remove duplicate rows (by key columns)',
    bulk_update: 'Update multiple rows by key',
    setup_sheet: 'Initialize new sheet with structure',
    import_and_format: 'Import data and apply formatting in one operation',
    clone_structure: 'Copy structure from one spreadsheet to another',
    generate_sheet: 'AI-powered sheet generation from natural language description',
    generate_template: 'Create reusable template from description',
    preview_generation: 'Preview proposed sheet structure before creating',
    audit_sheet: 'Comprehensive sheet audit (structure, quality, issues)',
    publish_report: 'Generate and publish formatted report',
    data_pipeline: 'Set up recurring data pipeline (import, transform, load)',
    instantiate_template: 'Create new sheet from template',
    migrate_spreadsheet: 'Migrate spreadsheet to different backend (Sheets → Excel, etc.)',
    batch_operations: 'Execute multiple composite operations atomically',
    build_dashboard: 'Generate interactive dashboard with charts and controls',
  },
  sheets_analyze: {
    scout: 'Quick preliminary scan (metadata, structure, type detection) ~200ms',
    comprehensive: 'Full analysis with 43 feature categories and AI scoring',
    analyze_data: 'Analyze specific data range (types, outliers, patterns)',
    analyze_formulas: 'Audit formulas (errors, volatile functions, dependencies)',
    analyze_structure: 'Analyze sheet structure (headers, layout, organization)',
    analyze_quality: 'Check data quality (missing values, duplicates, inconsistencies)',
    analyze_performance: 'Identify performance issues (volatile functions, large data, etc.)',
    analyze_understanding: 'AI understanding of sheet purpose and content',
    suggest_next_actions: 'Suggest next steps based on sheet analysis',
    auto_enhance: 'Apply suggested enhancements automatically',
    suggest_visualization: 'Suggest charts for data',
    generate_formula: 'Generate formula based on natural language description',
    detect_patterns: 'Find patterns in data (trends, seasonality, clusters)',
    discover_action: 'Discover potential high-impact actions',
    quick_insights: 'Get key insights without full analysis',
    explain_analysis: 'Explain analysis results in natural language',
    get_intelligence_report: 'Generate full intelligence report',
    diagnose_errors: 'Identify and explain formula errors',
    formula_health_check: 'Audit formula health across sheet',
    query_natural_language: 'Query sheet using natural language',
    semantic_search: 'Search cells by semantic meaning',
    plan: 'Create action plan based on analysis',
    execute_plan: 'Execute analysis-generated action plan',
    generate_actions: 'Generate executable actions from findings',
    schedule_intelligence: 'Schedule periodic analysis',
    cancel_intelligence: 'Cancel scheduled analysis',
  },
  sheets_fix: {
    clean: 'Auto-detect and fix data quality issues (whitespace, dates, types, etc.)',
    standardize_formats: 'Normalize date, currency, phone, and other formats',
    fill_missing: 'Fill empty cells using statistical strategies (forward fill, mean, median, etc.)',
    detect_anomalies: 'Identify statistical outliers (IQR, Z-score, isolation forest)',
    suggest_cleaning: 'AI recommendations for data cleaning (preview only)',
    fix: 'Fix generic data issues (catch-all, uses auto-detection)',
  },
  sheets_templates: {
    create: 'Save current spreadsheet as reusable template',
    list: 'List saved templates',
    get: 'Get template metadata',
    preview: 'Preview template before applying',
    apply: 'Create new spreadsheet from template',
    update: 'Update template definition',
    delete: 'Delete template',
    import_builtin: 'Import built-in template (predefined templates)',
  },
  sheets_bigquery: {
    connect: 'Connect BigQuery dataset as Connected Sheet',
    connect_looker: 'Connect Looker dashboard to spreadsheet',
    disconnect: 'Disconnect BigQuery/Looker connection',
    list_connections: 'List active BigQuery connections',
    get_connection: 'Get BigQuery connection details',
    query: 'Execute BigQuery SQL query',
    preview: 'Preview query results without saving',
    list_datasets: 'List available BigQuery datasets',
    list_tables: 'List tables in a dataset',
    get_table_schema: 'Get table schema',
    refresh: 'Refresh Connected Sheet data',
    cancel_refresh: 'Cancel ongoing refresh',
    import_from_bigquery: 'Import BigQuery data into sheet',
    export_to_bigquery: 'Export sheet data to BigQuery',
    create_scheduled_query: 'Create scheduled query (auto-refresh)',
    list_scheduled_queries: 'List scheduled queries',
    delete_scheduled_query: 'Delete scheduled query',
  },
  sheets_appsscript: {
    create: 'Create new Apps Script project',
    get: 'Get Apps Script project metadata',
    get_content: 'Get Apps Script source code',
    update_content: 'Update Apps Script source code',
    create_version: 'Create named version (checkpoint)',
    list_versions: 'List all versions',
    get_version: 'Get specific version',
    deploy: 'Deploy Apps Script (web app or execution API)',
    list_deployments: 'List all deployments',
    get_deployment: 'Get deployment details',
    run: 'Execute function in Apps Script',
    list_processes: 'List running script processes',
    get_metrics: 'Get execution metrics',
    undeploy: 'Remove deployment',
    install_serval_function: 'Install Serval AI function library',
  },
  sheets_auth: {
    status: 'Check authentication status',
    login: 'Initiate OAuth login flow',
    callback: 'Handle OAuth callback',
    logout: 'Logout and revoke tokens',
    setup_feature: 'Setup optional features (connectors, webhooks, sampling, federation)',
  },
  sheets_confirm: {
    request: 'Request user confirmation (destructive action)',
    get_stats: 'Get confirmation statistics',
    wizard_start: 'Start interactive wizard',
    wizard_step: 'Handle wizard step',
    wizard_complete: 'Complete wizard flow',
  },
  sheets_dependencies: {
    build: 'Build dependency graph for all formulas',
    analyze_impact: 'Analyze impact of deleting/modifying cells',
    detect_cycles: 'Find circular formula references',
    get_dependencies: 'Get dependencies of a cell',
    get_dependents: 'Get cells that depend on this cell',
    get_stats: 'Get dependency graph statistics',
    export_dot: 'Export dependency graph as GraphViz DOT format',
    model_scenario: 'Model what-if scenario (change values, see impacts)',
    compare_scenarios: 'Compare multiple scenarios side-by-side',
    create_scenario_sheet: 'Materialize scenario as new sheet',
  },
  sheets_quality: {
    validate: 'Validate data against rules (completeness, types, patterns)',
    detect_conflicts: 'Detect concurrent modification conflicts',
    resolve_conflict: 'Resolve merge conflict',
    analyze_impact: 'Analyze impact of proposed operation',
  },
  sheets_history: {
    list: 'List operation history',
    get: 'Get operation details',
    undo: 'Undo last operation',
    redo: 'Redo last undone operation',
    revert_to: 'Revert to a specific point in history',
    clear: 'Clear operation history',
    timeline: 'Get chronological timeline of changes',
    diff_revisions: 'Diff two revisions',
    restore_cells: 'Restore specific cells from past revision',
    stats: 'Get history statistics',
  },
  sheets_session: {
    set_active: 'Set active spreadsheet for context',
    get_active: 'Get active spreadsheet',
    get_context: 'Get session context (active sheet, preferences, connectors)',
    record_operation: 'Record operation in session history',
    get_last_operation: 'Get most recent operation',
    get_history: 'Get operation history',
    find_by_reference: 'Find spreadsheet by reference',
    get_preferences: 'Get user preferences',
    update_preferences: 'Update preferences (autoRecord, confirmDestructive, etc.)',
    set_pending: 'Set pending task',
    get_pending: 'Get pending tasks',
    clear_pending: 'Clear pending tasks',
    get_alerts: 'Get active alerts',
    acknowledge_alert: 'Acknowledge alert',
    clear_alerts: 'Clear all alerts',
    get_profile: 'Get user profile',
    update_profile_preferences: 'Update profile preferences',
    get_top_formulas: 'Get most-used formulas',
    record_successful_formula: 'Record successful formula for learning',
    reject_suggestion: 'Reject suggestion (for learning)',
    save_checkpoint: 'Save named checkpoint',
    load_checkpoint: 'Load checkpoint',
    delete_checkpoint: 'Delete checkpoint',
    list_checkpoints: 'List saved checkpoints',
    schedule_create: 'Create scheduled task',
    schedule_list: 'List scheduled tasks',
    schedule_cancel: 'Cancel scheduled task',
    schedule_run_now: 'Run scheduled task immediately',
    execute_pipeline: 'Execute analysis pipeline',
    reset: 'Reset session state',
  },
  sheets_transaction: {
    begin: 'Start atomic transaction',
    queue: 'Queue operation in transaction',
    commit: 'Commit all queued operations',
    rollback: 'Rollback transaction',
    status: 'Get transaction status',
    list: 'List active transactions',
  },
  sheets_federation: {
    list_servers: 'List connected remote MCP servers',
    get_server_tools: 'Get tools available on remote server',
    call_remote: 'Call tool on remote MCP server',
    validate_connection: 'Validate connection to remote server',
  },
  sheets_webhook: {
    watch_changes: 'Watch for spreadsheet changes',
    subscribe_workspace: 'Subscribe to workspace events',
    unsubscribe_workspace: 'Unsubscribe from events',
    list_workspace_subscriptions: 'List active subscriptions',
  },
  sheets_agent: {
    plan: 'Create multi-step execution plan',
    execute: 'Execute entire plan',
    execute_step: 'Execute single step',
    observe: 'Capture checkpoint',
    rollback: 'Revert to checkpoint',
    get_status: 'Get plan status',
    list_plans: 'List saved plans',
    resume: 'Resume interrupted plan',
  },
  sheets_compute: {
    evaluate: 'Evaluate formula or expression',
    aggregate: 'Compute aggregations (sum, avg, etc.)',
    statistical: 'Compute statistics (mean, stdev, percentiles, etc.)',
    regression: 'Perform linear/polynomial regression',
    forecast: 'Forecast time series values',
    matrix_op: 'Matrix operations (transpose, multiply, inverse, etc.)',
    pivot_compute: 'Compute pivot table programmatically',
    custom_function: 'Evaluate custom function on data',
    batch_compute: 'Batch multiple computations',
    explain_formula: 'Generate explanation of formula',
    sql_query: 'Execute SQL on in-memory table',
    sql_join: 'Join multiple ranges via SQL',
    python_eval: 'Execute Python code on data',
    sklearn_model: 'Train scikit-learn model',
    pandas_profile: 'Generate pandas profile',
    matplotlib_chart: 'Generate matplotlib chart',
  },
  sheets_connectors: {
    list_connectors: 'List available data connectors',
    configure: 'Configure connector credentials',
    query: 'Query connector endpoint',
    batch_query: 'Run multiple queries in parallel',
    status: 'Get connector health status',
    discover: 'Discover connector endpoints and schemas',
    subscribe: 'Subscribe to periodic data refresh',
    unsubscribe: 'Unsubscribe from refresh',
    list_subscriptions: 'List active subscriptions',
    transform: 'Apply transformations to query results',
  },
};

export const TOOL_DESCRIPTIONS_FULL = TOOL_DESCRIPTIONS;

// Schema
export const ToolDescriptionsSchema = z.object({
  descriptions: z.record(
    z.string().min(1),
    z.record(z.string().min(1), z.string().min(10))
  ),
});

export type ToolDescriptions = z.infer<typeof ToolDescriptionsSchema>;
