#!/bin/bash
#
# Check if metadata is synchronized with source code
# This prevents drift between TOOL_DEFINITIONS and metadata files
#
# Exit code:
#   0 = No drift (metadata is up to date)
#   1 = Drift detected (run npm run gen:metadata)
#
# Tracked files (all 5 generated by scripts/generate-metadata.ts):
#   1. package.json (description with tool/action counts)
#   2. src/schemas/index.ts (TOOL_COUNT, ACTION_COUNT constants)
#   3. src/schemas/annotations.ts (ACTION_COUNTS map)
#   4. src/mcp/completions.ts (TOOL_ACTIONS map)
#   5. server.json (full metadata)
#

set -e

echo "🔍 Checking for metadata drift..."
echo ""

# Define tracked files
TRACKED_FILES=(
  "package.json"
  "src/schemas/index.ts"
  "src/schemas/annotations.ts"
  "src/mcp/completions.ts"
  "server.json"
)

# Save original file contents to temp directory
TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

for file in "${TRACKED_FILES[@]}"; do
  if [ -f "$file" ]; then
    # Format the original file with prettier to ensure consistent comparison
    npx prettier "$file" > "$TEMP_DIR/$(basename $file).original" 2>/dev/null || cp "$file" "$TEMP_DIR/$(basename $file).original"
  fi
done

# Run generator
echo "📝 Running metadata generator..."

npm run gen:metadata --silent 2>/dev/null

# Ensure generated files conform to repo formatting rules.
# This avoids false-positive drift when generator output formatting differs
# from the project's Prettier defaults.
npx prettier --write src/mcp/completions.ts src/schemas/index.ts src/schemas/annotations.ts server.json >/dev/null 2>&1

# Check for changes in any tracked file
CHANGED_FILES=()
for file in "${TRACKED_FILES[@]}"; do
  original="$TEMP_DIR/$(basename $file).original"
  if [ -f "$original" ] && [ -f "$file" ]; then
    if ! diff -q "$file" "$original" >/dev/null 2>&1; then
      CHANGED_FILES+=("$file")
    fi
  fi
done

# If any files changed, show detailed diff and fail
if [ ${#CHANGED_FILES[@]} -gt 0 ]; then
  echo ""
  echo "❌ METADATA DRIFT DETECTED!"
  echo ""
  echo "The following ${#CHANGED_FILES[@]} file(s) are out of sync with schema definitions:"
  echo ""

  for file in "${CHANGED_FILES[@]}"; do
    echo "  • $file"
  done

  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "Diff output (showing changes):"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""

  for file in "${CHANGED_FILES[@]}"; do
    original="$TEMP_DIR/$(basename $file).original"
    echo "📄 $file:"
    echo ""
    diff -u "$original" "$file" 2>/dev/null || true
    echo ""
  done

  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  echo "🔧 To fix this drift:"
  echo ""
  echo "  1. Run the metadata generator:"
  echo "     npm run gen:metadata"
  echo ""
  echo "  2. Stage the updated files:"
  echo "     git add ${TRACKED_FILES[*]}"
  echo ""
  echo "  3. Commit the changes:"
  echo "     git commit -m 'chore: sync metadata with schema definitions'"
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  echo "💡 Tip: This happens when you modify schema files (src/schemas/*.ts)"
  echo "   without running the generator. Always run 'npm run gen:metadata'"
  echo "   after making schema changes."
  echo ""

  exit 1
fi

echo "✅ No metadata drift detected - all 5 files are synchronized"
echo ""
echo "Verified files:"
for file in "${TRACKED_FILES[@]}"; do
  echo "  ✓ $file"
done
echo ""

exit 0
