#!/bin/bash
#
# Check if metadata is synchronized with source code
# This prevents drift between TOOL_DEFINITIONS and metadata files
#
# Exit code:
#   0 = No drift (metadata is up to date)
#   1 = Drift detected (run npm run gen:metadata)
#
# Tracked files (all 5 generated by scripts/generate-metadata.ts):
#   1. package.json (description with tool/action counts)
#   2. src/schemas/index.ts (TOOL_COUNT, ACTION_COUNT constants)
#   3. src/schemas/annotations.ts (ACTION_COUNTS map)
#   4. src/mcp/completions.ts (TOOL_ACTIONS map)
#   5. server.json (full metadata)
#

set -e

echo "🔍 Checking for metadata drift..."
echo ""

# Define tracked files
TRACKED_FILES=(
  "package.json"
  "src/schemas/index.ts"
  "src/schemas/annotations.ts"
  "src/mcp/completions.ts"
  "server.json"
)

# Save current state (stage files so we can detect changes)
for file in "${TRACKED_FILES[@]}"; do
  if [ -f "$file" ]; then
    git add "$file" 2>/dev/null || true
  fi
done

# Run generator
echo "📝 Running metadata generator..."

npm run gen:metadata --silent 2>/dev/null

# Ensure generated files conform to repo formatting rules.
# This avoids false-positive drift when generator output formatting differs
# from the project's Prettier defaults (notably src/mcp/completions.ts).
npx prettier --write src/mcp/completions.ts server.json >/dev/null 2>&1

# Also format the tracked files in git's index to ensure apples-to-apples comparison
for file in "${TRACKED_FILES[@]}"; do
  if [ -f "$file" ]; then
    git show HEAD:"$file" 2>/dev/null | npx prettier --stdin-filepath "$file" > "/tmp/drift_check_$$.tmp" 2>/dev/null && \
      mv "/tmp/drift_check_$$.tmp" "$file.baseline" 2>/dev/null || rm -f "/tmp/drift_check_$$.tmp"
  fi
done

# Check for changes in any tracked file (compare against baseline if available)
CHANGED_FILES=()
for file in "${TRACKED_FILES[@]}"; do
  if [ -f "$file.baseline" ]; then
    if ! diff -q "$file" "$file.baseline" >/dev/null 2>&1; then
      CHANGED_FILES+=("$file")
    fi
    rm -f "$file.baseline"
  elif ! git diff --exit-code "$file" >/dev/null 2>&1; then
    CHANGED_FILES+=("$file")
  fi
done

# If any files changed, show detailed diff and fail
if [ ${#CHANGED_FILES[@]} -gt 0 ]; then
  echo ""
  echo "❌ METADATA DRIFT DETECTED!"
  echo ""
  echo "The following ${#CHANGED_FILES[@]} file(s) are out of sync with schema definitions:"
  echo ""

  for file in "${CHANGED_FILES[@]}"; do
    echo "  • $file"
  done

  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "Diff output (showing changes):"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""

  for file in "${CHANGED_FILES[@]}"; do
    echo "📄 $file:"
    echo ""
    git diff --color=always "$file" 2>/dev/null || true
    echo ""
  done

  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  echo "🔧 To fix this drift:"
  echo ""
  echo "  1. Run the metadata generator:"
  echo "     npm run gen:metadata"
  echo ""
  echo "  2. Stage the updated files:"
  echo "     git add ${TRACKED_FILES[*]}"
  echo ""
  echo "  3. Commit the changes:"
  echo "     git commit -m 'chore: sync metadata with schema definitions'"
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  echo "💡 Tip: This happens when you modify schema files (src/schemas/*.ts)"
  echo "   without running the generator. Always run 'npm run gen:metadata'"
  echo "   after making schema changes."
  echo ""

  exit 1
fi

echo "✅ No metadata drift detected - all 5 files are synchronized"
echo ""
echo "Verified files:"
for file in "${TRACKED_FILES[@]}"; do
  echo "  ✓ $file"
done
echo ""

exit 0
