/**
 * ServalSheets - Intent System
 *
 * Defines the intent types for the BatchCompiler
 * Tighten-up #8: Intent-based architecture
 */
import { z } from 'zod';
export declare const IntentTypeSchema: z.ZodEnum<{
    SET_VALUES: "SET_VALUES";
    CLEAR_VALUES: "CLEAR_VALUES";
    APPEND_VALUES: "APPEND_VALUES";
    ADD_SHEET: "ADD_SHEET";
    DELETE_SHEET: "DELETE_SHEET";
    UPDATE_SHEET_PROPERTIES: "UPDATE_SHEET_PROPERTIES";
    DUPLICATE_SHEET: "DUPLICATE_SHEET";
    INSERT_DIMENSION: "INSERT_DIMENSION";
    DELETE_DIMENSION: "DELETE_DIMENSION";
    MOVE_DIMENSION: "MOVE_DIMENSION";
    UPDATE_DIMENSION_PROPERTIES: "UPDATE_DIMENSION_PROPERTIES";
    APPEND_DIMENSION: "APPEND_DIMENSION";
    UPDATE_CELLS: "UPDATE_CELLS";
    REPEAT_CELL: "REPEAT_CELL";
    UPDATE_BORDERS: "UPDATE_BORDERS";
    MERGE_CELLS: "MERGE_CELLS";
    UNMERGE_CELLS: "UNMERGE_CELLS";
    AUTO_RESIZE_DIMENSIONS: "AUTO_RESIZE_DIMENSIONS";
    ADD_CONDITIONAL_FORMAT: "ADD_CONDITIONAL_FORMAT";
    UPDATE_CONDITIONAL_FORMAT: "UPDATE_CONDITIONAL_FORMAT";
    DELETE_CONDITIONAL_FORMAT: "DELETE_CONDITIONAL_FORMAT";
    SET_DATA_VALIDATION: "SET_DATA_VALIDATION";
    CLEAR_DATA_VALIDATION: "CLEAR_DATA_VALIDATION";
    ADD_CHART: "ADD_CHART";
    UPDATE_CHART: "UPDATE_CHART";
    DELETE_CHART: "DELETE_CHART";
    ADD_PIVOT_TABLE: "ADD_PIVOT_TABLE";
    UPDATE_PIVOT_TABLE: "UPDATE_PIVOT_TABLE";
    DELETE_PIVOT_TABLE: "DELETE_PIVOT_TABLE";
    SET_BASIC_FILTER: "SET_BASIC_FILTER";
    CLEAR_BASIC_FILTER: "CLEAR_BASIC_FILTER";
    SORT_RANGE: "SORT_RANGE";
    ADD_FILTER_VIEW: "ADD_FILTER_VIEW";
    UPDATE_FILTER_VIEW: "UPDATE_FILTER_VIEW";
    DELETE_FILTER_VIEW: "DELETE_FILTER_VIEW";
    ADD_SLICER: "ADD_SLICER";
    UPDATE_SLICER: "UPDATE_SLICER";
    DELETE_SLICER: "DELETE_SLICER";
    ADD_NAMED_RANGE: "ADD_NAMED_RANGE";
    UPDATE_NAMED_RANGE: "UPDATE_NAMED_RANGE";
    DELETE_NAMED_RANGE: "DELETE_NAMED_RANGE";
    ADD_PROTECTED_RANGE: "ADD_PROTECTED_RANGE";
    UPDATE_PROTECTED_RANGE: "UPDATE_PROTECTED_RANGE";
    DELETE_PROTECTED_RANGE: "DELETE_PROTECTED_RANGE";
    CREATE_DEVELOPER_METADATA: "CREATE_DEVELOPER_METADATA";
    UPDATE_DEVELOPER_METADATA: "UPDATE_DEVELOPER_METADATA";
    DELETE_DEVELOPER_METADATA: "DELETE_DEVELOPER_METADATA";
    ADD_BANDING: "ADD_BANDING";
    UPDATE_BANDING: "UPDATE_BANDING";
    DELETE_BANDING: "DELETE_BANDING";
    CUT_PASTE: "CUT_PASTE";
    COPY_PASTE: "COPY_PASTE";
    FIND_REPLACE: "FIND_REPLACE";
    ADD_DIMENSION_GROUP: "ADD_DIMENSION_GROUP";
    DELETE_DIMENSION_GROUP: "DELETE_DIMENSION_GROUP";
    UPDATE_DIMENSION_GROUP: "UPDATE_DIMENSION_GROUP";
}>;
export declare const IntentSchema: z.ZodObject<{
    type: z.ZodEnum<{
        SET_VALUES: "SET_VALUES";
        CLEAR_VALUES: "CLEAR_VALUES";
        APPEND_VALUES: "APPEND_VALUES";
        ADD_SHEET: "ADD_SHEET";
        DELETE_SHEET: "DELETE_SHEET";
        UPDATE_SHEET_PROPERTIES: "UPDATE_SHEET_PROPERTIES";
        DUPLICATE_SHEET: "DUPLICATE_SHEET";
        INSERT_DIMENSION: "INSERT_DIMENSION";
        DELETE_DIMENSION: "DELETE_DIMENSION";
        MOVE_DIMENSION: "MOVE_DIMENSION";
        UPDATE_DIMENSION_PROPERTIES: "UPDATE_DIMENSION_PROPERTIES";
        APPEND_DIMENSION: "APPEND_DIMENSION";
        UPDATE_CELLS: "UPDATE_CELLS";
        REPEAT_CELL: "REPEAT_CELL";
        UPDATE_BORDERS: "UPDATE_BORDERS";
        MERGE_CELLS: "MERGE_CELLS";
        UNMERGE_CELLS: "UNMERGE_CELLS";
        AUTO_RESIZE_DIMENSIONS: "AUTO_RESIZE_DIMENSIONS";
        ADD_CONDITIONAL_FORMAT: "ADD_CONDITIONAL_FORMAT";
        UPDATE_CONDITIONAL_FORMAT: "UPDATE_CONDITIONAL_FORMAT";
        DELETE_CONDITIONAL_FORMAT: "DELETE_CONDITIONAL_FORMAT";
        SET_DATA_VALIDATION: "SET_DATA_VALIDATION";
        CLEAR_DATA_VALIDATION: "CLEAR_DATA_VALIDATION";
        ADD_CHART: "ADD_CHART";
        UPDATE_CHART: "UPDATE_CHART";
        DELETE_CHART: "DELETE_CHART";
        ADD_PIVOT_TABLE: "ADD_PIVOT_TABLE";
        UPDATE_PIVOT_TABLE: "UPDATE_PIVOT_TABLE";
        DELETE_PIVOT_TABLE: "DELETE_PIVOT_TABLE";
        SET_BASIC_FILTER: "SET_BASIC_FILTER";
        CLEAR_BASIC_FILTER: "CLEAR_BASIC_FILTER";
        SORT_RANGE: "SORT_RANGE";
        ADD_FILTER_VIEW: "ADD_FILTER_VIEW";
        UPDATE_FILTER_VIEW: "UPDATE_FILTER_VIEW";
        DELETE_FILTER_VIEW: "DELETE_FILTER_VIEW";
        ADD_SLICER: "ADD_SLICER";
        UPDATE_SLICER: "UPDATE_SLICER";
        DELETE_SLICER: "DELETE_SLICER";
        ADD_NAMED_RANGE: "ADD_NAMED_RANGE";
        UPDATE_NAMED_RANGE: "UPDATE_NAMED_RANGE";
        DELETE_NAMED_RANGE: "DELETE_NAMED_RANGE";
        ADD_PROTECTED_RANGE: "ADD_PROTECTED_RANGE";
        UPDATE_PROTECTED_RANGE: "UPDATE_PROTECTED_RANGE";
        DELETE_PROTECTED_RANGE: "DELETE_PROTECTED_RANGE";
        CREATE_DEVELOPER_METADATA: "CREATE_DEVELOPER_METADATA";
        UPDATE_DEVELOPER_METADATA: "UPDATE_DEVELOPER_METADATA";
        DELETE_DEVELOPER_METADATA: "DELETE_DEVELOPER_METADATA";
        ADD_BANDING: "ADD_BANDING";
        UPDATE_BANDING: "UPDATE_BANDING";
        DELETE_BANDING: "DELETE_BANDING";
        CUT_PASTE: "CUT_PASTE";
        COPY_PASTE: "COPY_PASTE";
        FIND_REPLACE: "FIND_REPLACE";
        ADD_DIMENSION_GROUP: "ADD_DIMENSION_GROUP";
        DELETE_DIMENSION_GROUP: "DELETE_DIMENSION_GROUP";
        UPDATE_DIMENSION_GROUP: "UPDATE_DIMENSION_GROUP";
    }>;
    target: z.ZodObject<{
        spreadsheetId: z.ZodString;
        sheetId: z.ZodOptional<z.ZodNumber>;
        range: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>;
    payload: z.ZodRecord<z.ZodString, z.ZodUnknown>;
    metadata: z.ZodObject<{
        sourceTool: z.ZodString;
        sourceAction: z.ZodString;
        transactionId: z.ZodOptional<z.ZodString>;
        priority: z.ZodDefault<z.ZodOptional<z.ZodNumber>>;
        destructive: z.ZodDefault<z.ZodOptional<z.ZodBoolean>>;
        estimatedCells: z.ZodOptional<z.ZodNumber>;
    }, z.core.$strip>;
}, z.core.$strip>;
export type IntentType = z.infer<typeof IntentTypeSchema>;
export type Intent = z.infer<typeof IntentSchema>;
/**
 * Maps intent types to Google Sheets batchUpdate request types
 */
export declare const INTENT_TO_REQUEST_TYPE: Record<IntentType, string>;
/**
 * Destructive intent types (require safety rails)
 */
export declare const DESTRUCTIVE_INTENTS: Set<"SET_VALUES" | "CLEAR_VALUES" | "APPEND_VALUES" | "ADD_SHEET" | "DELETE_SHEET" | "UPDATE_SHEET_PROPERTIES" | "DUPLICATE_SHEET" | "INSERT_DIMENSION" | "DELETE_DIMENSION" | "MOVE_DIMENSION" | "UPDATE_DIMENSION_PROPERTIES" | "APPEND_DIMENSION" | "UPDATE_CELLS" | "REPEAT_CELL" | "UPDATE_BORDERS" | "MERGE_CELLS" | "UNMERGE_CELLS" | "AUTO_RESIZE_DIMENSIONS" | "ADD_CONDITIONAL_FORMAT" | "UPDATE_CONDITIONAL_FORMAT" | "DELETE_CONDITIONAL_FORMAT" | "SET_DATA_VALIDATION" | "CLEAR_DATA_VALIDATION" | "ADD_CHART" | "UPDATE_CHART" | "DELETE_CHART" | "ADD_PIVOT_TABLE" | "UPDATE_PIVOT_TABLE" | "DELETE_PIVOT_TABLE" | "SET_BASIC_FILTER" | "CLEAR_BASIC_FILTER" | "SORT_RANGE" | "ADD_FILTER_VIEW" | "UPDATE_FILTER_VIEW" | "DELETE_FILTER_VIEW" | "ADD_SLICER" | "UPDATE_SLICER" | "DELETE_SLICER" | "ADD_NAMED_RANGE" | "UPDATE_NAMED_RANGE" | "DELETE_NAMED_RANGE" | "ADD_PROTECTED_RANGE" | "UPDATE_PROTECTED_RANGE" | "DELETE_PROTECTED_RANGE" | "CREATE_DEVELOPER_METADATA" | "UPDATE_DEVELOPER_METADATA" | "DELETE_DEVELOPER_METADATA" | "ADD_BANDING" | "UPDATE_BANDING" | "DELETE_BANDING" | "CUT_PASTE" | "COPY_PASTE" | "FIND_REPLACE" | "ADD_DIMENSION_GROUP" | "DELETE_DIMENSION_GROUP" | "UPDATE_DIMENSION_GROUP">;
/**
 * High-risk intent types (require auto-snapshot)
 */
export declare const HIGH_RISK_INTENTS: Set<"SET_VALUES" | "CLEAR_VALUES" | "APPEND_VALUES" | "ADD_SHEET" | "DELETE_SHEET" | "UPDATE_SHEET_PROPERTIES" | "DUPLICATE_SHEET" | "INSERT_DIMENSION" | "DELETE_DIMENSION" | "MOVE_DIMENSION" | "UPDATE_DIMENSION_PROPERTIES" | "APPEND_DIMENSION" | "UPDATE_CELLS" | "REPEAT_CELL" | "UPDATE_BORDERS" | "MERGE_CELLS" | "UNMERGE_CELLS" | "AUTO_RESIZE_DIMENSIONS" | "ADD_CONDITIONAL_FORMAT" | "UPDATE_CONDITIONAL_FORMAT" | "DELETE_CONDITIONAL_FORMAT" | "SET_DATA_VALIDATION" | "CLEAR_DATA_VALIDATION" | "ADD_CHART" | "UPDATE_CHART" | "DELETE_CHART" | "ADD_PIVOT_TABLE" | "UPDATE_PIVOT_TABLE" | "DELETE_PIVOT_TABLE" | "SET_BASIC_FILTER" | "CLEAR_BASIC_FILTER" | "SORT_RANGE" | "ADD_FILTER_VIEW" | "UPDATE_FILTER_VIEW" | "DELETE_FILTER_VIEW" | "ADD_SLICER" | "UPDATE_SLICER" | "DELETE_SLICER" | "ADD_NAMED_RANGE" | "UPDATE_NAMED_RANGE" | "DELETE_NAMED_RANGE" | "ADD_PROTECTED_RANGE" | "UPDATE_PROTECTED_RANGE" | "DELETE_PROTECTED_RANGE" | "CREATE_DEVELOPER_METADATA" | "UPDATE_DEVELOPER_METADATA" | "DELETE_DEVELOPER_METADATA" | "ADD_BANDING" | "UPDATE_BANDING" | "DELETE_BANDING" | "CUT_PASTE" | "COPY_PASTE" | "FIND_REPLACE" | "ADD_DIMENSION_GROUP" | "DELETE_DIMENSION_GROUP" | "UPDATE_DIMENSION_GROUP">;
//# sourceMappingURL=intent.d.ts.map